version: '3'

# maintainer "Pavel Pavlenko <region23@gmail.com>"
services:

  mysql:
    container_name: blog_mysql
    build:
      context: ./mysql
      dockerfile: Dockerfile
    volumes:
      - ./mysql_data:/var/lib/mysql
    #restart: always
    environment:
     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
     MYSQL_DATABASE: ${MYSQL_DATABASE}
     MYSQL_USER: ${MYSQL_USER}
     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --character-set-server=utf8 --collation-server=utf8_general_ci


  phpmyadmin:
    container_name: blog_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
     MYSQL_ROOT_PASSWORD: root
     PMA_HOST: blog_mysql
    #restart: always
    depends_on:
     - mysql
    volumes:
     - /sessions

  php:
    container_name: blog_php
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./blog/:/var/www/blog
    #restart: always
    depends_on:
      - mysql

  caddy:
    container_name: blog_caddy
    build:
      context: ./caddy
      dockerfile: Dockerfile
    image: abiosoft/caddy
    depends_on:
      - mysql
      - phpmyadmin
      - php
    volumes:
      - ./caddy/.caddy:/root/.caddy/
      - ./blog/:/var/www/blog
    ports:
      - 80:80
      #- 443:443 
      - 2015:2015
      - 81:81